
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

# Paso 1: Aquí debes agregar el título y la descripción de las noticias junto con la anotación
# Si la noticia es sobre secuestro, anota 1; si no, anota 0
train_data = [
    ("Secuestro en la Ciudad de México deja a una persona desaparecida",
     "La policía investiga un secuestro en la colonia Roma", 1),
    ("La economía crece un 3% en el primer trimestre", "México experimenta un crecimiento económico este año", 0),
    ("Secuestradores piden rescate por una víctima en Monterrey",
     "El secuestro ocurrió la noche del miércoles en una zona residencial", 1),
    ("Nuevo récord en el mercado de valores", "El mercado de valores en México alcanza un máximo histórico", 0),
    ("Difunden video del secuestro del alcalde electo de Frontera Comalapa",
     "El hecho tuvo lugar en un café del ejido Terán, del municipio de Tuxtla Gutiérrez, captado por la cámara de un tráiler y posteriormente compartido en redes sociales",
     1),
    ("Arrestan a 4 policías y 6 falsos agentes en Taxco; los oficiales son acusados de secuestro",
     "Además, fue liberada una persona que se encontraba 'privada de su libertad' en la comandancia de la Policía Municipal",
     1),
    ("FGR vincula a Ovidio Guzmán con el presunto secuestro de 'El Mayo'; desconoce ubicación del hijo de 'El Chapo'",
     "Mediante una tarjeta informativa, la FGR reveló este jueves que obtuvo datos probatorios de una secuencia cronológica, la cual se inicia con la excarcelación de Ovidio 'G'",
     1),
    ("FGE detiene a 4 policías acusados de secuestro",
     "No pudieron acreditar ser agentes y liberaron a una persona que se encontraba privada de su libertad", 1),
    ("Detienen en Chihuahua a presunto delincuente acusado de secuestro y de al menos 5 homicidios en Hidalgo",
     "El sujeto contaba con cinco órdenes de aprehensión desde 2008", 1),
    ("Fiscalía de Quintana Roo resuelve dos casos de secuestro ocurridos en julio",
     "La dependencia asegura que los responsables fueron detenidos, mientras que las víctimas fueron liberadas y sus familias no tuvieron que realizar ningún pago por el rescate",
     1),
    ("FGR alista orden de aprehensión contra el 'chapito' involucrado en secuestro de 'El Mayo'",
     "A Joaquín Guzmán López se le acusa de privación ilegal de la libertad de una persona en territorio nacional para entregarla a las autoridades de otro país",
     1),
    ("VIDEO: Elementos de seguridad realizan simulacro de secuestro de avión en el AICM",
     "El ejercicio tiene como objetivo neutralizar actividades ilícitas en aeronaves, instalaciones y vehículos que pongan en riesgo la seguridad de los pasajeros, las instalaciones aeroportuarias y las operaciones aéreas",
     0),
    (
    "Caso Camila: Inicia juicio contra presuntos responsables del secuestro y feminicidio de la niña; defensa asegura que son inocentes",
    "Los abogados de Alfredo y Axel Alejandro aseguraron que su delito es ser hijos de Ana Rosa, la mujer que fue linchada",
    1),
    ("Autoridades investigan intento de robo o secuestro de padre del alcalde de Reynosa, Tamaulipas",
     "El padre del alcalde se limitó a decir que todo estaba bien, pero no brindó más detalles de lo sucedido", 1),
    ("Detienen a 3 expolicías municipales de Cajeme, Sonora, presuntamente implicados en secuestro agravado",
     "Se trata de dos hermanos e hijos de una regidora del partido Morena y un actual empleado del ayuntamiento de Cajeme, Sonora",
     1),
    ("'A Cuén lo mataron a la misma hora y en el mismo lugar donde me secuestraron a mí', afirma 'El Mayo' Zambada",
     "'Pidió a los gobiernos de México y EU ser transparentes y brindar la verdad acerca de mi secuestro y de la muerte de Héctor Cuén'",
     1),
    ("Secuestro de militares en Colombia pone en riesgo cese al fuego acordado con grupo disidente de las FARC",
     "Los soldados fueron interceptados y retenidos la tarde del viernes cuando realizaban 'acciones de control' en la zona colombiana de Guaviare",
     1),
    ("Alistan audiencia de Jorge Renán Solís, preso en India desde 2018; mexicano denuncia secuestro y tortura",
     "La Secretaría de Relaciones Exteriores informó que ha brindado asistencia consular y ha enviado más de 20 notas verbales para solicitar diversas gestiones en favor del connacional",
     1),
    (
    "Cuatro personas son vinculadas a proceso por su presunta participación en el delito de secuestro exprés con fines de robo",
    "El ilícito lo habrían cometido el pasado 9 de julio al privar de la libertad al conductor de un tractocamión de la marca Freigthliner",
    1),
    ("Fiscalía CDMX logra condena a 50 años de prisión a dos personas que participaron en secuestro exprés",
     "El Ministerio Público presentó el caso, ante un juez, de que ambas personas participaron en la privación de la libertad de un hombre en 2021",
     1),
    ("Versión de secuestro de 'El Mayo' revive caso de Álvarez Machain, acusado por asesinato de 'Kiki' Camarena",
     "Humberto Álvarez Machain fue secuestrado en México para enjuiciarlo en Estados Unidos, como circula la nueva versión de la detención del capo",
     1),
    ("Acusa el Mayo secuestro en México para llevarlo a EU",
     "Frank Pérez: 'fue emboscado, sometido por 6 uniformados y llevado a EU contra su voluntad', reporta Los Angeles Times",
     1),
    ("'El Mayo' Zambada: Captura o secuestro muestra que retrocedimos 35 años en la relación bilateral, dice experto",
     "Para Carlos Pérez Ricart esta incursión podría ser el inicio de una política mucho más unilateral porque tratan a México más como una 'fuente de problemas' que como su principal socio comercial",
     0),
    ("Sacerdote de Tuxtla Gutiérrez, Chiapas, niega amenazas y secuestro tras críticas a AMLO",
     "En su más reciente homilía, el sacerdote Miguel Cardona Valdivia opinó sobre la estrategia de 'abrazos no balazos' implementada por el presidente",
     0),
    ("Edomex: Taxista de aplicación sufre secuestro exprés a manos de un menor de edad",
     "El menor de edad presentaba una arma punzo cortante, por lo que policías de la SSEM lo detuvieron y presentaron ante la agencia del ministerio público",
     1),
    ("En Estados Unidos elevan alerta sobre grupo 'hacker' norcoreano Andariel por programas de secuestro de datos",
     "Andariel está volcado en el desarrollo de programas de secuestro de datos llamado 'ransomware'", 0),
    ("Investigan a expolicías detenidos por su presunta participación en secuestro exprés de empresario de Chalco",
     "El pasado 3 de mayo, la víctima viajaba a bordo de una camioneta tipo Pick Up sobre una vialidad del municipio de Chalco donde fue interceptado por los tripulantes de otro vehículo",
     1),
    ("Secuestro aumenta 36.3% en junio en México: ONG",
     "Además, la organización Alto al Secuestro, encabezada por Isabel Miranda de Wallace, reportó que hubo 2 secuestros masivos en Guerrero y el Estado de México",
     0),
    ("El Mayo acusa secuestro; sería una bomba entre México-EU", "Bajo Reserva", 0),
    ("Detienen a mujer en Edomex por secuestro y asesinato, hechos ocurridos en 2023",
     "La detenida fue trasladada al Centro Penitenciario y de Reinserción Social de la zona y quedó a disposición de un juez quien determinó vincularla a proceso con medida cautelar de prisión preventiva justificada",
     1),
    ("Un secuestro con humor sutil",
     "En 'No negociable', con Mauricio Ochmann y Tato Alexander, una pareja afronta sus problemas mientras él intenta liberarla",
     0),
    ("El otro secuestro operado por la DEA", "Héctor De Mauleón", 1),
    ("Integrantes del grupo delictivo 'Los Dinky's' son sentenciados a 75 años de prisión por secuestro",
     "Además, deberán pagar multa de 1 millón 242 mil 480 pesos, así como la cantidad de 171 mil 600 pesos como reparación del daño moral y 21 mil pesos como reparación del daño material",
     1),
    ("Reportan disminución de 26% en el delito de secuestro en el Edomex",
     "Los secuestros reportados en la entidad, del primero de enero al 24 de junio de este año, presentan una disminución con relación al mismo periodo de 2023",
     0),
    ("Detienen a tres por secuestro y posesión de armas en Edomex; podrían pertenecer a un grupo criminal de Jalisco",
     "El operativo antisecuestros se organizó tras una solicitud de apoyo ciudadano, para la liberación de dos personas que habían sido privadas de su libertad",
     1),
    ("Aún sin localizar, mujer privada de su libertad en Culiacán; Fiscalía abre investigación por secuestro",
     "Actualmente se desconoce el monto de dinero que exigen para liberarla, por lo que la autoridad judicial atiende este caso",
     1),
    ("Agresor de esposo de Nancy Pelosi también es declarado culpable de secuestro; encara cadena perpetua",
     "Esta sentencia se suma a la de 30 años de prisión, otorgada a David DePape por el ataque a Paul Pelosi, esposo de la expresidenta de la Cámara de Representantes",
     1),
    ("El secuestro del Congreso", "Kenia López Rabadán", 0),
    ("'Mamá, no mueras': revelan estremecedor audio del secuestro de argentinos en Gaza",
     "En la grabación se oye a la esposa del argentino David Cunio al pedir ayuda, y a sus pequeñas mellizas de 3 años, tosiendo aterrorizadas",
     1),
    ("Autoridades capitalinas detienen a 5 personas en Azcapotzalco e Iztapalapa por secuestro",
     "Elementos de la SSC, en coordinación con la FGJ, cumplimentaron las órdenes de aprehensión", 1),
    ("Edomex: condenan a 120 años de prisión a sujeto por el delito de secuestro exprés con la agravante de robo",
     "La Fiscalía General de Justicia del Estado de México acreditó la culpabilidad de Jorge Armando López Rivera", 1),
    ("Descartan secuestro tras hallazgo de migrantes africanos en finca de Culiacán, Sinaloa",
     "La Secretaría de Seguridad Pública del Estado dio a conocer que los migrantes certificaron que no se encontraban privados de su libertad, ya que habían rentado el inmueble para descansar",
     0),
    ("Revelan secuestro de ambientalista de Villa Madero, Michoacán",
     "Álvaro Alcahuter Villa es un activista ambiental de la localidad de El Zangarro y es reconocido por su comunidad en la defensa de los derechos ambientales como el acceso al agua y la protección de los bosques",
     1),
    ("Detienen en Nicolás Romero a sujeto relacionado con secuestro exprés de 2 personas",
     "Erik 'N' fue detenido en un domicilio de la colonia Santa Anita", 1),
    ("Hamas acusa a Israel de 'manipular' el video del secuestro de las mujeres soldado",
     "La organización islamista denuncia que Israel ha hecho 'una selección deliberada de imágenes y clips' para reforzar su narrativa sobre las presuntas agresiones a las mujeres secuestradas",
     0),
    (
    "Elementos de la Fiscalía y policía mexiquense liberan a víctima de secuestro en la Nicolás Romero; hay 6 detenidos",
    "En esa zona detectaron que personas ingresaban a un domicilio situado en la colonia Independencia, donde escucharon gritos de auxilio",
    1),
    ("Sentencian a 110 años de cárcel a hombre por secuestro y asesinato en Chalco",
     "Alejandro Aguilar Lara fue ingresado al Centro Penitenciario y de Reinserción Social de Chalco", 1),
    ("Reportan secuestro de profesor universitario en Navolato, Sinaloa",
     "Paul Omar Pérez fue privado de su libertad el martes pasado por tres hombres armados con rostros cubiertos que viajaban en un vehículo Spark color blanco",
     1),
    ("Liberan a más de 60 mujeres y niños víctimas de secuestro masivo en Nigeria",
     "Se sabe que operaciones militares obligaron a los grupos criminales a huir y abandonar a sus cautivos, sin embargo, familias aseguran haber pagado rescate",
     1),
    ("Sentencian a Eduardo 'N' a 60 años de prisión por secuestro exprés",
     "La Secretaría de Seguridad del Estado de México ha informado la detención de Eduardo Vargas por su posible participación en secuestro exprés al conductor de un tráiler el pasado 6 de junio del 2023",
     1),
    ("Asesinatos y secuestro de extranjeros en México, los casos que han marcado a México",
     "El 27 de abril, los surfistas Jake y Callum Robinson, así como Jack Carter Rhoad de EU desaparecieron en Baja California; el 16 de marzo la Embajada de Rusia en México informó sobre el secuestro de María 'R'",
     1),
    (
    "Obispo Salvador Rangel ingresó voluntariamente al motel, no fue secuestro exprés: revela Comisionado de Seguridad",
    "'Hasta donde sabemos entró voluntariamente al hotel, con una persona del mismo sexo, y esa persona después se retiró', declaró el jefe policiaco José Antonio Ortiz Guarneros",
    0),
    ("Abogado confirma secuestro exprés en desaparición de Salvador Rangel, obispo de Chilpancingo",
     "Pedro Bello, abogado del obispo emérito, señaló que sus captores usaron las tarjetas de crédito para comprar alcohol en tiendas de conveniencia, y pizzas en un negocio del municipio de Emiliano Zapata",
     1),
    ("Los misterios alrededor del caso del obispo Salvador Rangel: secuestro exprés, crimen organizado y narcotráfico",
     "Hasta el momento se desconoce si la desaparición, secuestro exprés del obispo Rangel está relacionada con el crimen organizado",
     1),
    ("Registran 3 crímenes y un secuestro de extranjeros en 2024",
     "Ante la ola de violencia en México el gobierno de Australia emitió alerta desde el 5 de abril", 1),
    ("Casadas a la fuerza y esclavizadas: ¿Qué fue de las 276 chicas nigerianas secuestradas por Boko Haram?",
     "Un centenar siguen desaparecidas; las que lograron escapar o fueron rescatadas todavía viven el trauma; el domingo se cumplen 10 años del secuestro",
     1),
    ("Hasta el 29 de febrero se registraron 25 mujeres secuestradas en México, revela Secretariado Ejecutivo",
     "De acuerdo con los datos, en enero de 2023 se registraron 13 presuntas víctimas de secuestro, mientras que en febrero del mismo año, la cifra aumentó a 21",
     0),
    ("Rescatan a cinco poblanos víctimas de secuestro en Sonora",
     "La denuncia fue recibida por parte de la Unidad Especializada en Combate al Secuestro (Uecs) de Puebla", 1),
    ("Puebla: población enardecida por secuestro de maestra persigue a los delincuentes y logra rescatar a la víctima",
     "Habitantes del municipio de Huejotzingo reportaron la quema de un vehículo donde presuntamente viajaban los secuestradores",
     1),
    ("Reseña de la película 'El secuestro del Papa': Marco Bellocchio y la dualidad catecúmena",
     "'El secuestro del Papa' se basa en un drama histórico que muestra el antisemitismo y abuso infantil de los soldados del Pontífice Pio IX; una crítica a esta institución religiosa",
     0),
    ("Juez da 75 años de prisión a 5 integrantes del CJNG por secuestro de estudiantes de cine en Jalisco",
     "Los jóvenes realizaban un trabajo cinematográfico en una casa y al retirarse de lugar fueron interceptados y privados de su libertad",
     1),
    ("Mueren en enfrentamiento dos elementos de la Guardia Estatal en Tamaulipas; desmienten secuestro de candidata",
     "A través de las redes sociales, está siendo difundido un video en el cual se observa a la candidata que es retirada del lugar donde hacía un recorrido proselitista",
     0),
    ("¿Se simuló un secuestro para asesinar al periodista Roberto Carlos Figueroa?", "Héctor De Mauleón", 1),
    ("AMLO revela secuestro de ingeniero que trabaja en construcción del Tren Maya",
     "López Obrador reconoció que en Chiapas y Tabasco se han incrementado los homicidios en las últimas semanas", 1),
    ("Vinculan a proceso a una mujer por secuestro y asesinato en Jocotitlán, Edomex",
     "La captura de Lourdes fue realizada como parte de una investigación llevada a cabo por la Fiscalía Mexiquense, en la que también realizaron una ampliación de inspección en un predio ubicado en el municipio de Jocotitlán",
     1),
    ("¡Ojo aquí! Esta es la nueva forma en que 'secuestran' tu WhatsApp",
     "¡Tu celular podría estar en peligro! Te explicamos en qué consiste el 'secuestro' de WhatsApp mediante un código QR",
     1),
    ("Aprehenden a 4 policías por implicación en delito de secuestro exprés en el Edomex",
     "Los detenidos fueron presentados ante la Agencia del Ministerio Público con sede en Metepec, donde se inició la carpeta de investigación",
     1),
    ("Netanyahu pide perdón a la familia de uno de los rehenes hallados muertos en Gaza",
     "Familias se niegan a responder las llamadas del primer ministro israelí", 0),
    ("Una charla con Saskia en EL UNIVERSAL", "", 0),
    (
        "Chile, Uruguay y Paraguay rechazan revocación de Venezuela sobre autorización a Brasil para custodiar embajada argentina en Caracas",
        "En las instalaciones hay seis opositores asilados, que fueron acusados por la fiscalía de propiciar actos violentos para desestabilizar al gobierno de Maduro",
        0),
    ("Netanyahu acusa a Hamas de rechazar todo en propuesta de cese el fuego en Gaza",
     "El primer ministro israelí enfrenta presión en su país y a nivel internacional para llegar a un acuerdo que permita la liberación de los rehenes",
     0),
    ("México, el país del 'todo bien' y los datos falsos", "Francisco Rivas", 0),
    ("EU planea presentar a Israel y Hamas un plan ultimátum de alto al fuego",
     "Si no es aceptado por las dos partes, podría suponer el abandono de las negociaciones", 0),
    (
        "El paso a pasito de la reforma judicial, parte 3 de 3: Jueces sin rostro; ¿protección en casos contra la delincuencia o riesgo a derechos humanos?",
        "QUÉ PASA CON...", 0),
    ("Líder opositora María Corina Machado alerta que régimen de Maduro busca violar asilo diplomático",
     "Recordó que 'el principio de la inviolabilidad de las misiones diplomáticas, según las Convenciones de Viena para las Relaciones Diplomáticas y para las Relaciones Consulares, es sagrado'",
     0),
    (
        "¿Por qué Brasil asumió la representación de la embajada de Argentina en Venezuela y cómo afecta a la actual crisis?",
        "El episodio podría tensar las relaciones entre el gobierno de Maduro y Lula da Silva", 0),
    ("Vehículo arrolla a un motociclista en la carretera Toluca-Tenango; automovilista se dio a la fuga",
     "Elementos de la Guardia Nacional realizaron abanderamiento en dos tramos, lo que causó asentamiento vehicular con dirección a Tenango del Valle",
     0),
    ("Brasil se dice 'sorprendida' y subraya que la misión argentina en Caracas es 'inviolable'",
     "El Gobierno brasileño destacó la inviolabilidad de instalaciones de la misión diplomática argentina, en los términos de la Convención de Viena",
     0),
    ("Al carajo con las instituciones y sobre todo con México", "Luis Obregón Lozada", 0),
    ("Ovidio Guzmán entra al programa de testigos protegidos, informa fuente de la DEA",
     "El caso no se presentará al público porque se calificó como clasificado", 0),
    ("Fiscalía de Chiapas desmiente que cadáver hallado en auto abandonado sea de alcalde electo de Frontera Comalapa",
     "Autoridades dijeron que siguen en la búsqueda de Aníbal Roblero, quien fue 'levantado' por un comando en Tuxtla Gutiérrez",
     0),
    ("Los operadores militares de Sheinbaum", "Raúl Rodríguez Cortés", 0),
    ("Premios Ariel 2024: ¿dónde ver las películas nominadas?",
     "Casi la totalidad de títulos nominados han sido estrenados en cines o plataformas y, algunas, como 'A cielo abierto', verán luz a finales del año",
     0),
    ("Republicanos acusan falsamente a haitianos de robar y comerse a mascotas; piden votar por Trump",
     "Desde J.D. Vance, el compañero de fórmula del expresidente, hasta legisladores y funcionarios influyentes han replicado un rumor contra la creciente población haitiana que vive en Springfield",
     0),
    ("Dan luz verde para el traslado de 'El Mayo' a la Corte de Brooklyn en Nueva York",
     "La jueza también suspendió los plazos del proceso ya abierto en Texas", 0),
    (
        "Investigan a policías municipales de Zumpango por presunto abuso de autoridad contra los tiktokers 'Familia Millonaria'",
        "Tendrán audiencia inicial para la formulación de imputación el próximo 2 de octubre", 0),
    ("FGR cita a funcionarios de Sinaloa relacionados a investigación del asesinato de Héctor Melesio Cuén",
     "De acuerdo con la investigación de la Fiscalía el hecho está relacionado a la excarcelación de Ovidio Guzmán", 0),
    ("Israel rescata cuerpos de 6 rehenes en plenas negociaciones para alto el fuego en Gaza",
     "Acuerdo de 'alto al fuego' tiene como objetivo la liberación de los rehenes israelís y palestinos", 0),
    ("Viven terror en Frontera Comalapa: 'Criminales están pasando casa por casa para avisar que estaban reclutados'",
     "Piden que se establezca un corredor humanitario que garantice la salida de la población 'cautiva' por los grupos armados",
     0),
    ("Réquiem por la democracia en México", "Luis Felipe Bravo Mena", 0),
    ("La 'bananización' de la relación bilateral México - EU", "Mario Alberto Puga", 0),
    ("Ismael 'El Mayo' Zambada cambia de opinión y acepta ser trasladado a Corte de NY",
     "Actualmente se encuentra en una prisión en El Paso, Texas", 0),
    ("Levantan al alcalde electo de Frontera Comalapa",
     "Aníbal Roblero Castillo ganó las elecciones del 2 de junio con el PVEM; fue plagiado en Tuxtla", 0),
    ("Republicanos, incluido J.D. Vance, esparcen rumor de que migrantes haitianos roban gatos y se los comen",
     "El candidato a vicepresidente de EU criticó el lunes en redes sociales la presencia en su estado de migrantes haitianos indocumentados",
     0),
    ("Israel lanza campaña para prevenir suicidios en medio de su peor crisis de salud mental",
     "El país registra aproximadamente 500 casos de suicidio anuales", 0),
    ("La mañanera de AMLO, 10 de septiembre, minuto a minuto",
     "Sigue lo más relevante de la conferencia del presidente Andrés Manuel López Obrador", 0),
    (
        "'Nunca emitiré una orden que vulnere el orden constitucional o los derechos humanos de nuestro pueblo', asegura Sheinbaum",
        "La presidenta electa señaló que seguirá convocando a la Sedena para 'la construcción de grandes proyectos estratégicos como los trenes de pasajeros hacia el norte del país y los nuevos puertos'",
        0),
    ("El rapero Sean 'Diddy' Combs pagará cantidad millonaria a un hombre que lo acusó de agresión sexual",
     "El rapero ha sido demandado este año por varias mujeres por conducta sexual inapropiada y agresión", 0),
    ("Secretaría de Seguridad de Sinaloa desmiente enfrentamientos armados en carretera México-Nogales",
     "Afirma que sólo corren rumores que no corresponden a la realidad, ya que en ningún punto del estado se han presentado nuevos enfrentamientos",
     0),
    ("VIDEO: Despliegan movilización militar en el nuevo hospital del IMSS-Bienestar en Sinaloa",
     "Las autoridades del estado aún no han dado a conocer el motivo del desplazamiento; sin embargo, se rumora que los militares respondieron al despojo de una camioneta cerca del lugar",
     0),
    ("Dan prisión preventiva a exmandos policiales",
     "Se llevó a cabo la audiencia inicial de imputación por cumplimiento de orden de aprehensión en contra de tres excomisarios de Aculco, Coatepec Harinas y Tlatlaya",
     0),
    (
        "Localizan a dos ciudadanos estadounidenses víctimas de extorsión telefónica; pedían 80 mil dólares por su liberación",
        "Arlene y Jeremy fueron reportados como desaparecidos, sin embargo, los encontraron antes de que sus familias realizaran algún pago o depósito por su rescate",
        1),
    ("Cuatro obras de arte para el museo de la 4T", "Carlos Loret de Mola", 0),
    ("Chocan Lilly Téllez y Noroña; senadora lo llama 'bellaco' durante discusión de reforma judicial",
     "La panista le exigió al presidente de la Mesa Directiva que presente al senador de MC, Daniel Barreda", 0),
    ("Trump acusa falsamente a inmigrantes en Ohio de comerse a perros y gatos",
     "Durante el debate televisado, Trump mencionó específicamente a Springfield, Ohio, la ciudad que está en el centro de las afirmaciones, y dijo que los inmigrantes se estaban apoderando de la ciudad",
     0),
    ("'Tu lugar está junto a Yunes y Murat', responde Álvarez Máynez a Claudio X. González por reforma judicial",
     "'Tú has violado la ley financiando campañas ilegales y has acordado con lo peor de la política mexicana', dijo el excandidato presidencial al empresario por la ausencia del senador Barreda",
     0),
    ("Matan a un niño de ocho años en robo de vehículo en Jilotepec, Edomex",
     "La Fiscalía del Estado de México investiga el caso tras el hallazgo del menor sin vida y el robo del automóvil; la comunidad exige respuestas y justicia para la víctima",
     0),
    ("Gobierno de Morelos condena ataque armado contra periodista Edgar Arroyo en Cuernavaca",
     "El periodista fue herido en el brazo al evitar un bloqueo frente a su casa; Las autoridades activan el Mecanismo de Protección y exigen investigación para dar con los responsables",
     0),
    ("En Nueva York recuerdan a víctimas de los atentados del 11 de septiembre; conmemoran 23 aniversario",
     "A la ceremonia conmemorativa acudieron los aspirantes a la Presidencia de Estados Unidos, Kamala Harris y Donald Trump",
     0),
    ("Sujetos armados atacan al periodista Edgar Arroyo coordinador de radio en La 99 en Morelos",
     "Arroyo evitó el bloqueo de sus atacantes pero recibió disparos y una de las balas le dio en un brazo", 0),
    ("Los Yunes, los Judas que traicionaron a la República", "Salvador García Soto", 0),
    ("Huyen de la quema de casas y del saqueo", "Héctor De Mauleón", 0),
    ("Aplanadora aprueba reforma judicial, con traición de Yunes",
     "Con un total de 86 votos a favor y 41 en contra se aprobó la reforma al poder judicial", 0),
    ("Debate Kamala Harris vs Donald Trump: Así fue el encontronazo entre ambos aspirantes a la presidencia de EU",
     "La vicepresidenta demócrata trató varias veces de provocar al expresidente republicano, recordándole en varias ocasiones la derrota electoral que él aún niega, y burlándose de algunas otras de sus afirmaciones falsas",
     0),
    (
        "Vinculan a proceso a sujetos por presunto robo de al menos 8 menores en Morelos; fueron capturados por intervenciones telefónicas",
        "De acuerdo con investigaciones federales, los niños eran presuntamente vendidos por 120 mil pesos a una red de trata de infantes con operaciones en Centroamérica",
        1),
    ("Perú rinde honores a Fujimori, el expresidente sentenciado por crímenes contra la humanidad", "Latinoamérica21",
     0),
    ("Presidente municipal de Cotija abandona el cargo",
     "Integrantes del cabildo buscarán que el Poder Legislativo designe un concejo ciudadano ante la ausencia del panista Juan Pablo Aguilar, quien, dicen, se fue a EU",
     0),
    ("El inicio del fatídico séptimo año", "Salvador García Soto", 0),
    ("'O dejan al PAN o nos vamos'; militantes exigen renuncia de Marko Cortés y otros que han manchado al partido",
     "Expresidentes municipales, exdiputados locales, encabezados por Manuel Gómez Morín, aseguraron que tienen el respaldo de exgobernadores como: Mauricio Kuri, Mauricio Vila, Diego Sinhué y Maru Campos",
     0),
    ("De la extorsión a Coca Cola en Morelos", "Héctor De Mauleón", 0),
    ("Alcalde de Taxco dará Grito de Independencia encerrado en el Ayuntamiento; sin verbena ni festejos",
     "Este año, el Grito de Independencia no se realizó en el sitio habitual, el edificio histórico Casa Borda, sin embargo la Secretaría de Cultura del estado no lo prestó al ayuntamiento por supuestos trabajos de rehabilitación",
     0),
    ("AMLO: 'Tengo la confianza que en 10 años estará mejor la impartición de justicia'",
     "López Obrador afirmó que la reforma permitirá realizar 'cambios importantes' en el Poder Judicial", 0),
    ("La mañanera de AMLO, 19 de septiembre, minuto a minuto",
     "Sigue lo más relevante de la conferencia del presidente Andrés Manuel López Obrador", 0),
    ("Este es el historial de operaciones remotas letales que Israel ha perpetrado en otros países",
     "El país rara vez se responsabiliza de tales ataques, y su ejército se negó a hacer comentarios; sin embargo el país tiene una larga historia de llevar a cabo operaciones remotas sofisticadas",
     0),
    ("Pobladores retienen a 12 policías en Veracruz; exigen la liberación de cinco personas detenidas",
     "Cuando los vecinos se preparaban para protestar, se desató un enfrentamiento con personas armadas que llegaron a dispararles, sin embargo, su manifestación se mantuvo",
     0),
    ("Sean 'Diddy' Combs vuelve a solicitar libertad bajo fianza en su caso de tráfico sexual",
     "La acusación formal describe a Combs como un hombre tan violento que causaba lesiones que a menudo tardaban días o semanas en sanar",
     0),
    ("AMLO asegura que se han registrado más del doble de homicidios en Guanajuato que en Sinaloa",
     "López Obrador expuso que, 'aunque es muy feo comparar', del 6 al 17 de septiembre se reportaron 40 homicidios dolosos en Sinaloa y 102 en Guanajuato",
     0),
    ("'La militarización no sirvió para mejorar la seguridad': Francisco Rivas, director del Observatorio Nacional", "",
     0),
    ("Néstor Núñez pide licencia y se va al gabinete de Sheinbaum", "El Caballito", 0),
    ("'Queremos disminuir los homicidios': Claudia Sheinbaum",
     "Ante la crisis de asesinatos e inseguridad que han dejado enfrentamientos entre Mayos y Chapitos en Culiacán, afirma que combatir a la delincuencia 'con poder de fuego' generaría 'una guerra'",
     0),
    ("Alberto Fujimori: 10 momentos clave de la vida política del fallecido expresidente",
     "Fujimori gobernó Perú entre 1990 y 2000, además fue condenado a 25 años de cárcel en 2009, pero en 2017 se le otorgó el indulto humanitario",
     0)
]

# Convertir el subconjunto de datos anotados a un DataFrame de pandas
df = pd.DataFrame(train_data, columns=['titulo', 'descripcion', 'es_secuestro'])

# Paso 2: Combinar el título y la descripción en una única columna de texto para el entrenamiento
df['texto_completo'] = df['titulo'] + " " + df['descripcion']

# Preprocesamiento: vectorización TF-IDF
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df['texto_completo'])  # Convertir los textos a vectores TF-IDF
y = df['es_secuestro']  # Etiquetas (1 o 0)

# Dividir en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Entrenar el clasificador Naive Bayes
clf = MultinomialNB()
clf.fit(X_train, y_train)

# Evaluación del modelo
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred, target_names=['No secuestro', 'Secuestro'], output_dict=True)

# Mostrar los resultados en español
print(f"Exactitud (Accuracy): {accuracy:.3f}")
print("\nMétricas por clase:\n")

for clase, valores in report.items():
    if clase in ['No secuestro', 'Secuestro']:
        print(f"Clase: {clase}")
        print(f"  Precisión (Precision): {valores['precision']:.2f}")
        print(f"  Sensibilidad (Recall): {valores['recall']:.2f}")
        print(f"  Equilibrio entre precisión y sensibilidad (F1-Score): {valores['f1-score']:.2f}")
        print(f"  Soporte (Número de ejemplos): {int(valores['support'])}\n")

# Función para predecir si una noticia está relacionada con secuestros
def predecir_secuestro(titulo, descripcion):
    texto_completo = titulo + " " + descripcion
    texto_vect = vectorizer.transform([texto_completo])
    prediccion = clf.predict(texto_vect)
    return prediccion[0]  # 1 si es secuestro, 0 si no lo es

# Ejemplo de predicción con una nueva noticia
titulo_ejemplo = "Sí, cuidado con el secuestro Existió un secuestro a plena luz el día según los hechos"
descripcion_ejemplo = "El incidente ocurrió en Ciudad de México y hubo 30 secuestrados"
print(f"\nPredicción para el ejemplo: {predecir_secuestro(titulo_ejemplo, descripcion_ejemplo)}")

